package br.com.shooping.list.application.dto.shoppinglist;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * DTO de resposta para um item de lista de compras.
 * Retornado pelos endpoints de gerenciamento de itens.
 */
@Schema(
    name = "ShoppingListItemResponse",
    description = "Shopping list item data"
)
public record ItemResponse(
        @Schema(
            description = "Item unique identifier (generated by database)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        Long id,

        @Schema(
            description = "Item name",
            example = "Rice",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String name,

        @Schema(
            description = "Item quantity",
            example = "2.5",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        BigDecimal quantity,

        @Schema(
            description = "Measurement unit",
            example = "kg",
            nullable = true,
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String unit,

        @Schema(
            description = "Unit price",
            example = "5.50",
            nullable = true,
            accessMode = Schema.AccessMode.READ_ONLY
        )
        BigDecimal unitPrice,

        @Schema(
            description = "Item status (PENDING or PURCHASED)",
            example = "PENDING",
            allowableValues = {"PENDING", "PURCHASED"},
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String status,

        @Schema(
            description = "Item creation timestamp (ISO-8601 UTC)",
            example = "2026-01-02T10:05:00.000Z",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
        Instant createdAt,

        @Schema(
            description = "Last update timestamp (ISO-8601 UTC)",
            example = "2026-01-02T15:30:00.000Z",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
        Instant updatedAt
) {}

