
package br.com.shooping.list.application.dto.shoppinglist;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.List;

/**
 * DTO de resposta completo para uma lista de compras.
 * Inclui detalhes completos da lista e contadores de itens.
 * O campo items é opcional e só é preenchido quando necessário (ex: GET /api/v1/lists/{id}).
 */
@Schema(
    name = "ShoppingListResponse",
    description = "Complete shopping list data with optional items array"
)
public record ShoppingListResponse(
        @Schema(
            description = "Shopping list unique identifier (generated by database)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        Long id,

        @Schema(
            description = "Owner user ID",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        Long ownerId,

        @Schema(
            description = "Shopping list title",
            example = "Monthly Groceries",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String title,

        @Schema(
            description = "Shopping list description",
            example = "Supermarket shopping for January",
            nullable = true,
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String description,

        @Schema(
            description = "List of items (populated only in GET /lists/{id}, null in other endpoints for optimization)",
            nullable = true,
            accessMode = Schema.AccessMode.READ_ONLY
        )
        List<ItemResponse> items,

        @Schema(
            description = "Total number of items in the list",
            example = "5",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        int itemsCount,

        @Schema(
            description = "Number of pending items (not purchased yet)",
            example = "3",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        int pendingItemsCount,

        @Schema(
            description = "Number of purchased items",
            example = "2",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        int purchasedItemsCount,

        @Schema(
            description = "List creation timestamp (ISO-8601 UTC)",
            example = "2026-01-02T10:00:00.000Z",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
        Instant createdAt,

        @Schema(
            description = "Last update timestamp (ISO-8601 UTC)",
            example = "2026-01-02T15:30:00.000Z",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
        Instant updatedAt
) {}

