package br.com.shooping.list.application.dto.auth;

import br.com.shooping.list.domain.user.AuthProvider;
import br.com.shooping.list.domain.user.UserStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;

/**
 * DTO para resposta de registro de usuário
 * Não expõe dados sensíveis como password hash
 */
@Schema(
    name = "AuthRegisterResponse",
    description = "User data returned after successful registration (no sensitive data)"
)
public record RegisterResponse(
        @Schema(
            description = "User unique identifier (generated by database)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        Long id,

        @Schema(
            description = "User email address",
            example = "user@example.com",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String email,

        @Schema(
            description = "User full name",
            example = "John Doe",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        String name,

        @Schema(
            description = "Authentication provider (LOCAL or GOOGLE)",
            example = "LOCAL",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        AuthProvider provider,

        @Schema(
            description = "User account status (ACTIVE, INACTIVE, BLOCKED)",
            example = "ACTIVE",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        UserStatus status,

        @Schema(
            description = "Account creation timestamp (ISO-8601 UTC)",
            example = "2026-01-02T10:30:00.000Z",
            accessMode = Schema.AccessMode.READ_ONLY
        )
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timezone = "UTC")
        Instant createdAt
) {}

